### ISSUE TITLE
CVSS 3.1 Environmental score calculation issues

### ISSUE THREAD

**Issue by fossbrandon** [oliverhamboerger/CvssSuite#2]
When I attempt to create a CvssBase object with the command `var cvss_v31 = CvssSuite.Create("CVSS:3.1/AV:P/AC:L/PR:H/UI:N/S:C/C:N/I:L/A:H/E:X/RL:T/RC:C/CR:M/IR:L/AR:H/MAV:P/MAC:L/MPR:L/MUI:X/MS:U/MC:N/MI:X/MA:H");` it returns me the correct base score of 5.7 and temporal score of 5.5. However, it calculates the Environmental score and subsequently, the overall score as 6.5 instead of 6.0 like they should be. I believe the code is incorrect when calculating the environmental score if some of the metrics are labeled as 'Not Defined' rather than one of its other potential values.

**Comment by 0llirocks** [comment]
@FossBrandon thank you for your report, I‘ll take a look at it on Sunday and keep you updated.

**Comment by fossbrandon** [comment]
Great! I'll take a look as well and update this if I find the cause of these issues. Thank you.

**Comment by 0llirocks** [comment]
@FossBrandon I updated the package, please check if everything works now, thanks!

**Comment by fossbrandon** [comment]
@oliverhamboerger Thanks for looking into that and fixing it so quickly! It works correctly for me now.
